// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://freshbox.framer.website
// Generated: 2026-07-30T02:17:02.234Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#ffffff' | '#e9e9e9' | '#482820' | '#7f675c' | '#920711' | '#5f070d' | '#fff7e8' | '#fc9e25';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter Display' | 'Tanker' | 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600';

export type SpacingToken = '1px' | '30px' | '40px' | '52px' | '60px' | '88px' | '100px' | '120px' | '130px' | '150px' | '416px' | '436px';

export type RadiusToken = '10px' | '16px' | '20px' | '30px' | '40px' | '999px';

export type DurationToken = never;
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
